maintable:
  intcol:
    type: int
    name: intcol
    order: 0
    pkey: True
  strcol:
    type: string
    name: strcol
    order: 1
    pkey: True
  boolcol:
    type: bool
    name: boolcol
    order: 2
  floatcol:
    type: float
    name: floatcol
    order: 3
