version: "3.9"
services:
  router:
    build: ../../router
    hostname: router
    ports:
      - "27604:27604"
  apiserver:
    depends_on:
      - router
    build: .
    hostname: apiserver
    restart: always
    scale: 2
