name: Push CI (Test)
on: push
jobs:
  buildchanges:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [client]
    steps:
      - name: Set up Go for ${{ matrix.project }}
        uses: actions/setup-go@v2
        with:
          go-version: "1.17"
      - name: Check out monorepo
        uses: actions/checkout@v2
      - name: Run Go tests
        run: go test ./...
        working-directory: ./${{ matrix.project }}
