name: Pull Request CI (Test)
on: pull_request
jobs:
  buildchanges:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [client, router]
    steps:
      - name: Set up Go for ${{ matrix.project }}
        uses: actions/setup-go@v2
        with:
          go-version: "1.17"
      - name: Check out monorepo
        uses: actions/checkout@v2
      - name: Run Go tests
        run: make test
        working-directory: ./${{ matrix.project }}
      - name: Validate Go build
        run: make build
        working-directory: ./${{ matrix.project }}
